**Basics of NumPy**

In [1]:
import numpy as np

**Basic of Numpy**

In [2]:
a = np.array([5,6,7])

In [3]:
print(a)

[5 6 7]


In [4]:
b = np.array([[2.0,5.0,6.0],[8.0,2.0,9.0]])

In [5]:
print(b)

[[2. 5. 6.]
 [8. 2. 9.]]


In [6]:
#dimentions
a.ndim

1

In [7]:
b.ndim

2

In [8]:
#shape
a.shape

(3,)

In [9]:
b.shape

(2, 3)

In [10]:
#type
a.dtype

dtype('int32')

In [11]:
b.dtype

dtype('float64')

In [12]:
#size
a.itemsize

4

In [13]:
b.itemsize

8

In [14]:
a.nbytes

12

**Accessing/Changing specific elements, rows, columns etc.**

In [15]:
a = np.array([[10,21,22,2,8,9,12],[12,1,2,4,9,6,5]])
print(a)

[[10 21 22  2  8  9 12]
 [12  1  2  4  9  6  5]]


In [16]:
# get specific elements
a[0,3]

2

In [17]:
a[1,4]

9

In [18]:
a[0,-1]

12

In [19]:
a[1,-4]

4

In [20]:
print(a)

[[10 21 22  2  8  9 12]
 [12  1  2  4  9  6  5]]


In [21]:
print(a[0])

[10 21 22  2  8  9 12]


In [22]:
print(a[0,:])

[10 21 22  2  8  9 12]


In [23]:
print(a[:,0])

[10 12]


In [ ]:
#changing the elements

In [24]:
print(a)

[[10 21 22  2  8  9 12]
 [12  1  2  4  9  6  5]]


In [25]:
a[0,2] = 12

In [26]:
print(a)

[[10 21 12  2  8  9 12]
 [12  1  2  4  9  6  5]]


In [27]:
a[:,3] = 3
print(a)

[[10 21 12  3  8  9 12]
 [12  1  2  3  9  6  5]]


In [28]:
a[:,3] = [1,2]
print(a)

[[10 21 12  1  8  9 12]
 [12  1  2  2  9  6  5]]


In [29]:
#3d array
b = np.array([[[3,4],[6,5]],[[1,5],[9,8]]])
print(b)

[[[3 4]
  [6 5]]

 [[1 5]
  [9 8]]]


**Initializing Different Arrays**

In [30]:
#all zeros matrics
np.zeros(4)

array([0., 0., 0., 0.])

In [31]:
#numpy.zeros(shape, dtype=float, order='C')
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.zeros((4,5,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [34]:
np.ones(4)

array([1., 1., 1., 1.])

In [35]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [37]:
np.full((3,3),3,dtype = 'float32')

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]], dtype=float32)

In [38]:
a

array([[10, 21, 12,  1,  8,  9, 12],
       [12,  1,  2,  2,  9,  6,  5]])

In [39]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [40]:
#ramdom decimals
np.random.rand(4,2)

array([[0.54415841, 0.07434511],
       [0.59580139, 0.22991326],
       [0.29614659, 0.7287159 ],
       [0.82781396, 0.4279311 ]])

In [ ]:
np.random.random_sample(a.shape)

array([[0.66810182, 0.04286826, 0.80662102, 0.06367593, 0.33900996,
        0.99249191, 0.28182805],
       [0.75296279, 0.61781132, 0.06784062, 0.38769982, 0.32090717,
        0.87911674, 0.88696183]])

In [41]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [42]:
arr = np.array([[11,12,5]])
a1 = np.repeat(arr, 3, axis = 1)
print(a1)

[[11 11 11 12 12 12  5  5  5]]


**Mathematics**

In [43]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [44]:
a +5 

array([6, 7, 8, 9])

In [45]:
a - 3

array([-2, -1,  0,  1])

In [46]:
a*3

array([ 3,  6,  9, 12])

In [47]:
a/3

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [48]:
a//3

array([0, 0, 1, 1], dtype=int32)

In [49]:
b = np.array([5,6,7,8])

In [50]:
a + b

array([ 6,  8, 10, 12])

In [51]:
a**3

array([ 1,  8, 27, 64], dtype=int32)

In [52]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [53]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

**Linear Algebra**

In [54]:
a = np.full((3,4),5)
b = np.full((4,5),4)
print(a)
print(b)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


In [55]:
a*b

ValueError: operands could not be broadcast together with shapes (3,4) (4,5) 

In [56]:
np.matmul(a,b)

array([[80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80]])

In [58]:
c = np.identity(5)
c

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
np.linalg.det(c)

1.0

**Statistics**

In [60]:
s = np.array([[1,2,3],[4,5,6]])

In [61]:
s

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
np.min(s, axis = 1)

array([1, 4])

In [63]:
np.max(s)


6

In [64]:
np.sum(s)

21

In [65]:
np.sum(s, axis = 1)

array([ 6, 15])

**Reorganizing Arrays**

In [66]:
b1 = np.array([[2,4,6,8],[1,3,5,7]])
b1

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

In [67]:
a1 = b1.reshape((4,2))

In [68]:
print(a1)

[[2 4]
 [6 8]
 [1 3]
 [5 7]]


In [84]:
# a1 = b1.reshape((2,3))

In [70]:
#vertical stacking 
v1 = np.array([2,4,6,8])
v2 = np.array([1,3,4,5])

In [71]:
np.vstack([v1,v2])

array([[2, 4, 6, 8],
       [1, 3, 4, 5]])

In [72]:
np.hstack([v1,v2])

array([2, 4, 6, 8, 1, 3, 4, 5])

**Import Data from a file**

In [75]:
data = np.array([[1.,2.,3.,4.,5.],[6.,7.,8.,9.,10.]])

In [76]:


# Save the array to a text file
np.savetxt("array.txt", data, delimiter=",")


In [77]:
Data = np.genfromtxt('array.txt', delimiter = ',')

In [78]:
print(Data)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


**Boolean Masking and Advanced Indexing**

In [79]:
Data > 5

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True]])

In [80]:
Data == 2

array([[False,  True, False, False, False],
       [False, False, False, False, False]])

In [81]:
a = np.array([10,20,30,40,50,60,70,80,90,100])

In [82]:
a[[2,5,8]]

array([30, 60, 90])

In [83]:
np.any(a> 50, axis = 0)

True